"""empty message

Revision ID: 3c583f62511d
Revises: c859c2b57fa2
Create Date: 2019-09-18 19:11:26.246043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c583f62511d'
down_revision = 'c859c2b57fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd_hash', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwd_hash')
    # ### end Alembic commands ###
